import type { Metadata } from 'next';
import { Arapey, Geist_Mono } from 'next/font/google';
import './globals.css';

const arapey = Arapey({
  weight: '400',
  variable: '--font-arapey',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='pt-br'>
      <body
        className={`${arapey.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
